### ISSUE TITLE
crash on system missing snap

### ISSUE THREAD

**Issue by kevinwortman** [JaredDyreson/Tuffix-Lib#6]
On an Ubuntu derivative without `snap`, we get the following crash:

```vagrant@vagrant:/tuffix$ tuffix
tuffix 0.1.0

usage:

    tuffix <command> [argument...]

where <command> and [argument...] match one of the following:

Traceback (most recent call last):
  File "/usr/bin/tuffix", line 14, in <module>
    print_usage(DEFAULT_BUILD_CONFIG)
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Driver.py", line 30, in print_usage
    commands = all_commands(build_config)
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Commands.py", line 502, in all_commands
    return [AddCommand(build_config),
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Commands.py", line 250, in __init__
    self.mark = AddRemoveHelper(build_config, self.name)
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Commands.py", line 90, in __init__
    self.container = KeywordContainer(build_config)
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Keywords.py", line 713, in __init__
    C481Keyword(build_config),
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Keywords.py", line 492, in __init__
    self.Eclipse = EclipseKeyword(self.build_config)
  File "/usr/local/lib/python3.8/dist-packages/Tuffix/Editors.py", line 212, in __init__
    raise EnvironmentError(f'could not find snap')
OSError: could not find snap
```

It seems like the only place we are using snaps are to install Eclipse. Could we either cut Eclipse, or install it from tarball?

**Comment by JaredDyreson** [comment]
In previous builds of Tuffix, I attempted to alleviate this issue by installing from a tar ball too. Since installing a tar ball does not leave any real way of uninstalling it, I decided to try and make a class that could construct Debian packages of a tar ball. That sort of worked but was more of a case by case basis. I don't know the legality of putting pre-made Debian installers on our PPA. We could just cut the Eclipse editor for the initial launch and we can make a Debian installer but make it "hidden" from average users until we figure out the logistics of that?

**Comment by JaredDyreson** [comment]
Also, it seems that 481 might be in need of it based on previous requirements (not sure why AI needs it but hey), and since there are a lot of different options available, I'd say we could let students figure out how to install it themselves if they really want it?

**Comment by JaredDyreson** [comment]
Closing this issue and making a new issue labeled help wanted in regards to `eclipse`
